### PR TITLE
Reduce indent by using if/else on low cardenality matches

### PR DESCRIPTION
**Pull request by bryce-anderson**
This PR shouldn't change behavior or performance in any material way.

Nested match statements cause a lot of indentation. For low cardinality
matches an if/else tree is more space friendly especially when there is
no need for the terminating else statement.

Ran rustfmt on workload/src/lib.rs which removed many brace enclosed
blocks that contained a single statement.

### CODE REVIEW

**Comment by brayniac** [comment]
Looks good. I don't see any obvious performance issues with this change.

**Comment by bryce-anderson** [comment]
When writing this I noticed a lot of calls of the form
```rust
let _ = self.queue.push(..);
```
At first I thought that it was a mistake and you wanted to `.unwrap()` but upon further inspection I saw that the mpmc queue is bound in size. This pattern is intentional so as to not panic when a work queue overflows, correct?

**Comment by brayniac** [comment]
Correct. Granted, for the `prepare()`, this should not be the case. However in `run()` this would be the general case for non-ratelimited workload generation.

**Comment by bryce-anderson** [comment]
Is knowledge of the overflow interesting? I would think it valuable in the context of network benchmarking. Perhaps it could/should  be logged in a counter or something.

**Comment by brayniac** [comment]
I think there's value in adding stats to rpc-perf in general. This is one of the things I was pondering last night. #73 to track and discuss further

**Pull request merged**
