### PR TITLE
thrift request refactoring

### PR DESCRIPTION
**Pull request by brayniac**
Refactored the thrift request lib to follow the builder pattern. This should make it more flexible short-term for supporting more complex requests. This change also removes the right-shift of the buffer when framing the request

### CODE REVIEW

**Comment by bryce-anderson** [comment]
How far are you planning to take the thrift codec code? There are already a few 'thrift for rust' libraries around (see [thrust](https://github.com/thehydroimpulse/thrust) for an example) that might at least serve as an example. 

A related question is how versatile you want to make you codec stack. Thrift is a layered protocol with a transport layer and a protocol layer which begs for a decoding pipeline that can be modularized (again, much like netty `ChannelHandler` concept) which could end up being a bit of work. As for the individual stages of such a pipeline I would think a `trait` would be the best fit: using an `enum` will change the vtable based dispatch with what amounts to a series of hard coded `if else` branching that will get nasty really fast.

A framework for building a codec stack would be really helpful if a goal is to support thriftmux messages. The plethora of combinations are illustrated [here](https://github.com/twitter/finagle/blob/develop/finagle-thriftmux/src/main/scala/com/twitter/finagle/thriftmux/Netty3.scala) by all the different `ChannelHander` classes (that code is actually for downgrading a thriftmux connection to the raw thrift protocol, but it illustrates the point in one file). On that topic, mux is actually something I've been interested in and have a bit of code locally for decoding the messages but its only at a start and under heavy flux because I'm still learning about the rust library ecosystem.

**Comment by brayniac** [comment]
Good points. I need to do a bit more canvassing internally to see what all the requirements will be. I believe there would be interest in thriftmux. 

My immediate needs are less complex. I only need Framed Binary for the time being. One of the things I'm struggling with is how the thrift support in rpc-perf can be made to function for a given IDL. For instance, can the workload TOML be extended to allow the request to be generated based on the TOML? How do we allow others to use rpc-perf for testing non-public thrift services?

I have a few issues with the existing 'thrift for rust' solutions. I've looked at both [thrust](https://github.com/thehydroimpulse/thrust) and [terminal_thrift](https://github.com/terminalcloud/thrift) though have spent more time on terminal_thrift. First issue is that they are tightly coupled to operation on TCP streams and are sync. This is probably okay for many use-cases, but with rpc-perf we need to continue to use MIO and operate in an async manner. There also seems to be a lack of active development on both of them. I'd be open to borrowing ideas, or using a modified fork, but those projects don't seem to be in a healthy state currently.

**Comment by bryce-anderson** [comment]
The existing Thrift solutions for rust are a bit stale considering the typical pace of rust projects (including the compiler itself). I just meant there might be some codec code worth looking at. I stand behind the idea of using `trait`s to form the protocol stack if you want to future-proof for alternative transports etc: it should be much more flexible. Making a protocol stack will be somewhat awkward with mio due to the inversion of control from the reactor pattern (which I find much more difficult in rust than java/scala: a GC soaks up a lot of noise).

I don't know enough about the thrift protocol to be sure but I suspect it would be possible to essentially re-specify the IDL in the toml file and have rust build a model out of it which it can interpret for the requests. Again just a guess, but I suspect it should be possible to only care about certain RPC calls so  the _entire_ IDL is not necessary. That also begs the question of do you want to validate the response or just make sure you get one?

**Comment by brayniac** [comment]
@bryce-anderson +1 on using `trait`s for the protocol stack. For the responses,  I would like to parse the response to categorize it. This could get complicated, short term I'm okay with just `Complete` vs `Incomplete`

I'd like to take a crack at using the TOML for describing at least the request portion. For now, I'm considering merging this PR. I think the current pattern is an improvement and avoids the right shift of the buffer. This should also make it more flexible to extend when supporting more complex Thrift requests.

If you have interest in working on improvements beyond this, please feel free to do so. We should probably log some issues to track the next steps.

**Comment by bryce-anderson** [comment]
Sounds good! I'll try to make a habit of creating WIP PR's for things I'm working on so you can provide feedback and we can avoid duplicating work etc.

**Pull request merged**
