### PR TITLE
Add ttl option for Redis inline set command

### PR DESCRIPTION
**Pull request by tejom**
This is a small change to add an optional 3rd parameter to redis's set command to set the ttl option.

### CODE REVIEW

**Comment by brayniac** [comment]
@tejom - When you get a chance, can you sign the CLA? Also be-sure the commit reflects your corporate email address. Thanks!

**Comment by tejom** [comment]
Forgot to go back and do that. The commit author is using my twitter email

**Comment by brayniac** [comment]
@tejom - awesome! Can you rebase against master? Landed a few other things since this opened.

**Comment by tejom** [comment]
Hey yeah I just did that.

**Pull request merged**
